 kind: Deployment
 apiVersion: apps/v1
 metadata:
    name: mrDevops
 spec:
    replicas: 2
    selector:  #tells the controller which pods to watch/belong to
      matchLables: 
         app: mrDevops
      template:
         metadata:
           labels:
             app: mrDevops
         spec: 
          containers:
             - name: mrDevops
               image: sainathmitalakar/pipeline-demo
                 imagePullPolicy: Always
                 ports:
                 - containerPort: 80
